apiVersion: v1
kind: Service
metadata:
  name: template
spec:
  selector:
    app: template
  ports:
    - port: 80
      protocol: TCP
      targetPort: template
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: ko://github.com/matzew/kodev/cmd/template
          ports:
            - containerPort: 8080
              protocol: TCP
              name: template
